apiVersion: apps/v1
kind: Deployment
metadata:
   name: gol-app
spec: 
  replicas: 5
  selector:
    matchLabels: 
     app: gol
  template: 
    metadata: 
      name: gol-pod
      labels:
        app: gol
    spec: 
     containers:
      - name: gol 
        image: abbanapurinaresh/myimages:gol1 
        ports: 
        - containerPort: 8080 
